overrides: coala.yaml

name: coala-brackets
description: coala extension for Brackets

language: node

configuration:
  template_dir:
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - .gitignore: coala-gitignore.jj2
